let vol = 1+4+'volvo'
console.log('This is year = ', vol)
console.log('This is laddu  = ', typeof vol)

let vol2 = "volvo"+(4+5)
console.log('This is year = ', vol2)
console.log('This is laddu  = ', typeof vol2)



let year;
console.log('This is year = ', year)
console.log('This is laddu  = ', typeof year)


year = 2025
console.log('This is year = ', year)
console.log('This is laddu  = ', typeof year)

year = "prashanth"
console.log('This is year = ', year)
console.log('This is laddu  = ', typeof year)

year = {}
console.log('This is year = ', year)
console.log('This is laddu  = ', typeof year)

year =[]
console.log('This is year = ', year)
console.log('This is laddu  = ', typeof year)

year = true
console.log('This is year = ', year)
console.log('This is laddu  = ', typeof year)

year = null;
console.log('This is year = ', year)
console.log('This is laddu  = ', typeof year)



console.log('Header of the HTML to be displayed');
console.log('I am from Javascript welcome to the world');
//let
//let keyword can be updated
//let keyword cannot be redeclared
let a = 30
console.log('this is let keyword number a  =' +a);
a = 40
console.log('this is let keyword number a  =' +a);
let b = 50
console.log('this is let keyword number a  =' +(a+b));
//c = 34
//console.log('this is let keyword number a  =' +c);
//const
//const keyword cannot be updated
//const keyword cannot be redeclared

const c = 45
console.log('this is let keyword number c  =' +c);
//c =56
console.log('this is let keyword number c  =' +c);

const newYear = {'fYear' : '2025', 'mYear' : 'Prashanth'}
console.log(newYear);
newYear.mYear = 'Developer'
console.log(newYear);
newYear.fYear = '2026';
console.log(newYear);
var yellow = 'white'
console.log(yellow)
var blue = 'green'
console.log('blue')
yellow = 'zebra';
console.log(yellow)



