let a = 10
let b = "10"
let abc;
let xzy = null
console.log(typeof abc, typeof xzy)
console.log(abc==xzy)
console.log(abc===xzy)
console.log(a==b)
console.log(a===b)
console.log(typeof a, typeof b)
console.log(a+Number(b))
console.log(a=b)

mahesh = false
console.log(mahesh)
mahesh = true
console.log(mahesh)
mahesh = !mahesh
console.log(mahesh)

let maxAge = 15
let output = maxAge >18 ? 'Eligible for vote' : 'Stay away from voting'
console.log(output)
let num3 = 25;
let num4 = '69';
console.log(num3 && num4)
console.log(num3 || num4)
let age = 30
if(age>18){
    console.log('eligible to voting')
}else{
    console.log('not eligible for voting')
}

console.log(true || true)
console.log(false||false)
console.log(true||false)
console.log(false||true)

console.log(num3 +-num4)
console.log(true && true)
console.log(false&&false)
console.log(true&&false)
console.log(false&&true)



let num1 = 30;
let num2 = "40"
console.log(typeof num1, typeof num2)

if(isNaN(num2)){
    console.log('I am unable to process addition because it is not a number')
}else{
    console.log(num1+Number(num2));
}
//console.log(num1+Number(num2));

console.log("This is prashanth gatadi");
let strName
console.log(strName);
console.log(typeof strName);
let strFName = null;
console.log(strName);
console.log(typeof strName);
